### ISSUE TITLE
Support for Azure DevOps Services

### ISSUE THREAD

**Issue by mpseidel** [CitrusAndriessen/tfs-mail-sendgrid#1]
Hey there,

Is there a reason why this task does only target Azure DevOps Server (onprem)?

Would love to try it in the cloud 🙂

**Comment by jpbroeders** [comment]
> Hey there,
> 
> Is there a reason why this task does only target Azure DevOps Server (onprem)?
> 
> Would love to try it in the cloud 🙂

Hi,

No there is no specific reason why it only target the on-premise version.
Probably because I tested it and used it in the on-premise version. 🙂

I will make it available for the cloud version to.

Thanks for your comment.

**Comment by jpbroeders** [comment]
> > Hey there,
> > Is there a reason why this task does only target Azure DevOps Server (onprem)?
> > Would love to try it in the cloud 🙂
> 
> Hi,
> 
> No there is no specific reason why it only target the on-premise version.
> Probably because I tested it and used it in the on-premise version. 🙂
> 
> I will make it available for the cloud version to.
> 
> Thanks for your comment.

Hi,

It's now also available for Azure DevOps (Cloud)
Good luck with it!

**Comment by mpseidel** [comment]
thanks! 👍

**Comment by jpbroeders** [comment]
> thanks! 👍

I guess it works fine!?
