### ISSUE TITLE
Add a CC entry

### ISSUE THREAD

**Issue by SenseiJoe** [CitrusAndriessen/tfs-mail-sendgrid#2]
Would like to have a CC entry.

**Comment by jpbroeders** [comment]
Good feature and pretty simple to implement.
I think there will be a new version at the end of this week.

**Comment by jpbroeders** [comment]
> Would like to have a CC entry.

Good feature and pretty simple to implement.
I think there will be a new version at the end of this week.

**Comment by jpbroeders** [comment]
> > Would like to have a CC entry.
> 
> Good feature and pretty simple to implement.
> I think there will be a new version at the end of this week.

Add the new functionality already.
The new version can be downloaded in the marketplace
Thanks for the suggestion.

**Comment by SenseiJoe** [comment]
Thanks for the quick response, works great!
